
spring:
  application:
    name: jpastudy
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true


logging:
  level:
    jdbc.sqlonly: debug
